### ISSUE TITLE
Potentially: send paths to core app to ignore watching

### ISSUE THREAD

**Issue by loppear** [nxus/clientjs#1]
As watchify will handle changes to the entry apps and will be modifying the output files, independent of the Nxus app watcher.

**Comment by mjreich** [comment]
There is an 'ignore' app config value that is used to ignore certain paths from watching, BUT this is set on App() construction. I think the best place to do this is add in the ignore glob to https://github.com/nxus/core/blob/master/src/Application.js#L204

**Comment by loppear** [comment]
Yes, we can workaround in project config by re-listing the client/output dirs, so this is just nice-to-have automation, and would require modifying Application to let modules register additional ignore paths.
